name: Test changes in Push Request and comment

on:
  push:
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      tests-result: ${{ steps.set_output.outputs.tests-result }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

      - name: Test
        id: test
        run: npm run test-log
        continue-on-error: true

      - name: Set output for tests-result
        id: set_output
        run: echo "::set-output name=tests-result::${{steps.test.outcome}}"  

      - name: Upload test.log file
        uses: actions/upload-artifact@master
        if: ${{steps.test.outcome == 'Failure'}} # Upload only if tests failed  
        with:
          name: testlog
          path: test.log

  comment:
    name: Comment test results
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Notify that all tests passed
        run: echo 'ALL TESTS PASSED!'   
        if:  ${{needs.test.outputs.tests-result == 'Success'}}

      - name: Notify that tests did not pass
        run: echo 'TESTS DID NOT PASS'  
        if:  ${{needs.test.outputs.tests-result == 'Failure'}}    

      - name: Download log file
        uses: actions/download-artifact@master
        if:  ${{needs.test.outputs.tests-result == 'Failure'}}
        with:
          name: testlog  

      - name: Show content of test.log
        if:  ${{needs.test.outputs.tests-result == 'Failure'}}
        run: cat test.log
