name: Test changes in Pull Request and comment

# on:
#   pull_request:
#     types: [opened, reopened, edited]

on:
  push:
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      tests-result: ${{ steps.set_output.outputs.tests-result }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

      - name: Test
        id: test
        run: npm run test-log
        continue-on-error: true

      - name: Create tests_result file with 'success'
        run: echo 'success' > testsresult.txt
        if: ${{steps.test.outcome == 'Success'}} 

      - name: Create tests_result file with 'failure'
        run: echo 'failure' > testsresult.txt
        if: ${{steps.test.outcome == 'Failure'}} 

      - name: Upload tests_result file
        uses: actions/upload-artifact@master  
        with:
          name: testsresult
          path: testsresult.txt

      - name: Upload test.log file
        uses: actions/upload-artifact@master
        if: ${{steps.test.outcome == 'Failure'}} # Upload only if tests failed  
        with:
          name: testlog
          path: test.log
      - name: Set output for the job
        id: set_output
        run: echo "::set-output name=tests-result::${{steps.test.outcome}}"    
  comment:
    name: Comment test results
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download testsresult file
        uses: actions/download-artifact@master
        with:
          name: testsresult
          
      - name: Read testsresult.txt file and set output parameter
        id: set_output
        run: echo "::set-output name=TESTS_RESULT::$(<testsresult.txt)" 

      - name: Notify that all tests passed
        run: echo 'ALL TESTS PASSED!'   
        if:  ${{steps.set_output.outputs.TESTS_RESULT == 'success'}}

      - name: Notify that tests did not pass
        run: echo 'TESTS DID NOT PASS'  
        if:  ${{steps.set_output.outputs.TESTS_RESULT == 'failure'}}    

      - name: Download log file
        uses: actions/download-artifact@master
        if:  ${{steps.set_output.outputs.TESTS_RESULT == 'failure'}}
        with:
          name: testlog  

      - name: Show content of test.log
        if:  ${{steps.set_output.outputs.TESTS_RESULT == 'failure'}}
        run: cat test.log
  testOutput:
    name: Test use of needs.job.outputs.name pattern
    runs-on: ubuntu-latest
    needs: test 
    steps:
      - name: Print the output of job named "test"
        run: echo "needs.test.outputs.tests-result = ${{ needs.test.outputs.tests-result }}"   

