name: Test changes in Pull Request and comment

on:
  pull_request:
    
jobs:
  test:
    name: Test on pull request
    runs-on: ubuntu-latest
    env:
      TEST_RESULT: 'success'
    steps:
      - name: Check PR started
        run: echo "Started Pull Request"

      - name: Create a test.txt file
        run: echo 'Hello, world!' > test.txt

      - name: Print content of test.txt 1
        run: |
          value=`cat test.txt`
          echo $value  
          echo "::set-env name=TEST_RESULT::$value"

      - name: Print content of test.txt 2
        run:  echo 'TEST_RESULT is' $TEST_RESULT

      - name: Print content of test.txt 3
        run:  echo 'TEST_RESULT is' ${{ env.TEST_RESULT }}

      - name: comment on Pull Request
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/issues/:issue_number/comments
          repository: ${{ github.repository }}
          issue_number: ${{ github.event.number }}
          body: ${{ env.TEST_RESULT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check PR started
        run: echo "My comment should be on PR page"    
