name: Test changes in Pull Request and comment

on:
  pull_request:
    
jobs:
  test:
    name: Test on pull request
    runs-on: ubuntu-latest
    steps:
      - name: Check PR started
        run: echo "Started Pull Request"

      - name: Create a test.txt file
        run: echo 'Hello, world!' > test.txt

      - name: Print content of test.txt
        run: cat test.txt  

      - name: comment on Pull Request
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/issues/:issue_number/comments
          repository: ${{ github.repository }}
          issue_number: ${{ github.event.number }}
          body: test.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check PR started
        run: echo "My comment should be on PR page"    
