name: Test changes in Pull Request and comment

on:
  pull_request:
    
jobs:
  test:
    name: Test on pull request
    runs-on: ubuntu-latest
    steps:
      - name: Check PR started
        run: echo "Started Pull Request"

