name: Test changes in Pull Request and comment

# on:
#   pull_request:
#     types: [opened, reopened, edited]

on:
  push:
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test-log
        continue-on-error: true
      - name: Upload log file
        uses: actions/upload-artifact@master
        with:
          name: testlog
          path: test.log
  comment:
    name: Comment test results
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download log file
        uses: actions/download-artifact@master
        with:
          name: testlog
      - name: Show content of test.log
        run: cat test.log
